### ISSUE TITLE
Listener only triggers Update event

### ISSUE THREAD

**Issue by KennyGoers** [alexjlockwood/kyrie#18]
I've tried KyrieDrawables both with path animations and no animations, calling start only ever triggers the Update event on the listener, am I missing something? I'm trying to trigger an associated animation upon completion of the animation, but the updated comes early and I never get other animations.

Thoughts?

**Comment by alexjlockwood** [comment]
Sorry... I'm dumb.

![2f6kgk](https://user-images.githubusercontent.com/1380747/43612136-3f1aeeae-9660-11e8-9203-84e2eec06964.jpg)

**Comment by alexjlockwood** [comment]
I just published `0.1.3` with the fix.

**Comment by KennyGoers** [comment]
Giving it a try now (you missed the readme.md on version number ;)

**Comment by KennyGoers** [comment]
So, I tried out 0.1.3, getting a lot more update events, but only update events, should there be a complete event?

**Comment by alexjlockwood** [comment]
Hmm... are you sure?
I tested it using the sample app... I changed the class in [this file](https://github.com/alexjlockwood/kyrie/blob/20f726694591482595f0603aabe61eedefa8140c/sample/src/main/java/com/example/kyrie/SampleListenerAdapter.java) to this:

```
final class SampleListenerAdapter extends KyrieDrawable.ListenerAdapter {
  @NonNull private final SeekBar seekBar;

  public SampleListenerAdapter(@NonNull SeekBar seekBar) {
    this.seekBar = seekBar;
  }

  @Override
  public void onAnimationStart(KyrieDrawable drawable) {
    super.onAnimationStart(drawable);
  }

  @Override
  public void onAnimationPause(KyrieDrawable drawable) {
    super.onAnimationPause(drawable);
  }

  @Override
  public void onAnimationResume(KyrieDrawable drawable) {
    super.onAnimationResume(drawable);
  }

  @Override
  public void onAnimationCancel(KyrieDrawable drawable) {
    super.onAnimationCancel(drawable);
  }

  @Override
  public void onAnimationEnd(KyrieDrawable drawable) {
    super.onAnimationEnd(drawable);
  }

  @Override
  public void onAnimationUpdate(@NonNull KyrieDrawable drawable) {
    final float playTime = drawable.getCurrentPlayTime();
    final float totalDuration = drawable.getTotalDuration();
    final float fraction = playTime / totalDuration;
    seekBar.setProgress(Math.round(fraction * seekBar.getMax()));
  }
}
```

And then I set breakpoints on all of the methods. They all seem to be getting called for me.

Could you post the code you are using?

**Comment by KennyGoers** [comment]
Would it be possible for me to send you the code directly? I'm not paranoid
about my own code, but its partially related to a project I'm working on.
Its a single Kotlin file that constructs a KyrieDrawable and plays the
result in an ImageView...

**Comment by KennyGoers** [comment]
Throw out my stupidity, events are working just fine after updating to
0.1.3, no idea how, but I was still using 0.1.1 in the cache and not the
most recent, I blame it on alpha 3.3 AS
